document.getElementById("button").addEventListener("click", translateToEmoji);

function translateToEmoji() {
    const inputText = document.getElementById("input").value.toLowerCase();
    const outputDiv = document.getElementById("output");

    const emojiMap = {
        // 😄 EMOTIONS
        happy: "😊",
        sad: "😢",
        love: "❤️",
        laugh: "😂",
        angry: "😠",
        surprised: "😲",
        excited: "🤩",
        bored: "😐",
        tired: "😴",
        crying: "😭",
        cool: "😎",
        scared: "😱",
        thinking: "🤔",
        kiss: "😘",
        grin: "😁",
        shy: "☺️",
        wink: "😉",
        hug: "🤗",

        // 🌍 FLAGS
        india: "🇮🇳",
        usa: "🇺🇸",
        uk: "🇬🇧",
        japan: "🇯🇵",
        germany: "🇩🇪",
        france: "🇫🇷",
        brazil: "🇧🇷",
        canada: "🇨🇦",
        italy: "🇮🇹",
        china: "🇨🇳",

        // 🧑 PEOPLE / GENDER
        boy: "👦",
        girl: "👧",
        man: "👨",
        woman: "👩",
        baby: "👶",
        father: "👨‍👧",
        mother: "👩‍👧",
        teacher: "🧑‍🏫",
        student: "🧑‍🎓",
        police: "👮",
        doctor: "🧑‍⚕️",

        // 🐶 ANIMALS
        dog: "🐶",
        cat: "🐱",
        lion: "🦁",
        tiger: "🐯",
        elephant: "🐘",
        monkey: "🐵",
        bear: "🐻",
        pig: "🐷",
        rabbit: "🐰",
        panda: "🐼",
        frog: "🐸",
        mouse: "🐭",
        bird: "🐦",
        cow: "🐮",
        horse: "🐴",
        fish: "🐟",

        // 🎨 COLORS
        red: "🟥",
        blue: "🟦",
        green: "🟩",
        yellow: "🟨",
        orange: "🟧",
        purple: "🟪",
        black: "⬛",
        white: "⬜",
        brown: "🟫",

        // 🧸 OBJECTS
        phone: "📱",
        laptop: "💻",
        book: "📖",
        car: "🚗",
        bike: "🚲",
        clock: "⏰",
        light: "💡",
        key: "🔑",
        camera: "📷",
        gift: "🎁",
        house: "🏠",
        money: "💰",
        lock: "🔒",
        chair: "🪑",
        umbrella: "☂️",

        // ⚽ SPORTS
        football: "⚽",
        basketball: "🏀",
        cricket: "🏏",
        tennis: "🎾",
        golf: "🏌️",
        volleyball: "🏐",
        baseball: "⚾",
        swimming: "🏊",
        running: "🏃",
        skiing: "⛷️",
        cycling: "🚴",

        // 🍕 FOOD & DRINKS
        pizza: "🍕",
        burger: "🍔",
        fries: "🍟",
        hotdog: "🌭",
        sandwich: "🥪",
        taco: "🌮",
        sushi: "🍣",
        ramen: "🍜",
        rice: "🍚",
        noodles: "🍝",
        soup: "🥣",
        egg: "🥚",
        cheese: "🧀",
        chicken: "🍗",
        meat: "🥩",
        salad: "🥗",
        bread: "🍞",
        apple: "🍎",
        banana: "🍌",
        watermelon: "🍉",
        grapes: "🍇",
        coffee: "☕",
        tea: "🍵",
        juice: "🧃",
        milk: "🥛",
        beer: "🍺",
        wine: "🍷",
        cocktail: "🍸",
        cake: "🎂",
        icecream: "🍦",
        chocolate: "🍫",
        donut: "🍩",
        cookie: "🍪",

        // 🧭 TRAVEL & PLACES
        hotel: "🏨",
        school: "🏫",
        hospital: "🏥",
        restaurant: "🍽️",
        park: "🏞️",
        airport: "🛫",
        beach: "🏖️",
        mountain: "⛰️",
        temple: "⛩️",
        church: "⛪",
        mosque: "🕌",
        city: "🏙️",
        desert: "🏜️",
        volcano: "🌋",
        bridge: "🌉",
        trainstation: "🚉",

        // 🚀 TRANSPORT
        bus: "🚌",
        train: "🚆",
        plane: "✈️",
        rocket: "🚀",
        ship: "🚢",
        tram: "🚋",
        taxi: "🚕",
        metro: "🚇",
        boat: "🛥️",

        // 💬 EXPRESSIONS
        hello: "👋",
        bye: "👋",
        thanks: "🙏",
        sorry: "😔",
        yes: "👍",
        no: "👎",
        ok: "👌",
        help: "🆘",
        idea: "💡",
        wow: "😮",

        // 🔣 SYMBOLS
        check: "✔️",
        cross: "❌",
        star: "⭐",
        fire: "🔥",
        heart: "❤️",
        peace: "✌️",
        smile: "☺️",
        warning: "⚠️",
        info: "ℹ️",
        question: "❓",
        exclamation: "❗",
        music: "🎵",
        sun: "☀️",
        moon: "🌙",
        snow: "❄️",
        rain: "🌧️",
        cloud: "☁️",
    };

    const words = inputText.split(" ");
    const emojiOnly = words
        .map(word => emojiMap[word])
        .filter(Boolean) // remove undefined if word not found
        .join("");

    outputDiv.innerText = emojiOnly || "❓";
}
